version: '3.8'

services:
  shiny01:
    image: legion949/img_chemsolver:v0.0.1  # Imagen personalizada para Shiny
    container_name: shiny01
    ports:
      - "3838:8080"
    restart: always  # Reiniciar automáticamente en caso de fallos

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Puerto para la página inicial y redirección
    volumes:
      - ./home:/usr/share/nginx/html  # Carpeta para la página inicial
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Configuración de Nginx
    depends_on:
      - shiny01
    restart: always
    
    
    
